const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Modal, Button} = wp.components;
const {withState} = wp.compose;

try {
	var icon = require('./icon') .default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

registerBlockType('presentation/plus-block', {
	title: 'Plus Block',
	icon: icon,
	category: 'nikon-presentations',
	attributes: {
		caption1: {
			type: 'string',
			default: 'ICONIC'
		},
		subtitle1: {
			type: 'string',
			default: 'BRAND'
		},
		text1: {
			type: 'string',
			default: 'The Nikon image is associated with credibility, quality, and satisfaction for our consumers.',
		},
		caption2: {
			type: 'string',
			default: 'OUTSTANDING',
		},
		subtitle2: {
			type: 'string',
			default: 'INNOVATION',
		},
		text2: {
			type: 'string',
			default: 'Nikon has paved the way to be the leader in continuing to introduce new technologies.',
		},
		caption3: {
			type: 'string',
			default: 'UNIQUE',
		},
		subtitle3: {
			type: 'string',
			default: 'CONSUMER EXPERIENCE',
		},
		text3: {
			type: 'string',
			default: 'We excite people’s passion for exploring through our unique consumer experience.',
		},
		caption4: {
			type: 'string',
			default: 'STRONG',
		},
		subtitle4: {
			type: 'string',
			default: 'PARTNERSHIP',
		},
		text4: {
			type: 'string',
			default: 'Nikon fosters healthy vision by selecting customers who embody the same yearning.',
		},
	},
	edit({className, attributes, setAttributes}) {
		const infoWrapperItem = (i,  placeholderSubtitle, placeholderTitle, placeholderText) => {
			return <div className="info_wrapper_item">
				<div>
          <span className="white_caption">
            <PlainText value={attributes[`caption${i}`]} placeholder={placeholderSubtitle} className="white_caption"
					   onChange={content => setAttributes({[`caption${i}`]: content})}/>
          </span>

					<span className="gold_caption">
            <PlainText value={attributes[`subtitle${i}`]} placeholder={placeholderTitle} className="gold_caption"
					   onChange={content => setAttributes({[`subtitle${i}`]: content})}/>
          </span>
				</div>
				<p>
					<PlainText value={attributes[`text${i}`]} placeholder={placeholderText}
							   onChange={content => setAttributes({[`text${i}`]: content})}/>
				</p>

			</div>;
		};

		return <div className="info">
			<div className="info_wrapper">

				{infoWrapperItem(1, 'ICONIC', 'BRAND', 'The Nikon image is associated with credibility, quality, and satisfaction for our consumers.')}
				{infoWrapperItem(2, 'OUTSTANDING', 'INNOVATION', 'Nikon has paved the way to be the leader in continuing to introduce new technologies.')}
				{infoWrapperItem(3, 'UNIQUE', 'CONSUMER EXPERIENCE', 'We excite people’s passion for exploring through our unique consumer experience.')}
				{infoWrapperItem(4, 'STRONG', 'PARTNERSHIP', 'Nikon fosters healthy vision by selecting customers who embody the same yearning.')}

				<div className="info_wrapper_decor">
					<img src={imgSrc("plus.svg")} alt="icon"/>
				</div>
			</div>
		</div>;
	},
	save({attributes}) {

		const infoWrapperItem = (i) => {
			return (attributes[`caption${i}`] || attributes[`subtitle${i}`] || attributes[`text${i}`]) &&
				<div className="info_wrapper_item">
					{(attributes[`caption${i}`] || attributes[`subtitle${i}`]) &&
					<div>
						{attributes[`caption${i}`] &&
						<span className="white_caption">{attributes[`caption${i}`]}</span>
						}
						{attributes[`subtitle${i}`] &&
						<span className="gold_caption">{attributes[`subtitle${i}`]}</span>
						}
					</div>
					}
					{attributes[`text${i}`] &&
						<p>{attributes[`text${i}`]}</p>
					}
				</div>
		};

		return <div className="info opacity_animate animated">
			<div className="info_wrapper">
				{infoWrapperItem(1)}
				{infoWrapperItem(2)}
				{infoWrapperItem(3)}
				{infoWrapperItem(4)}
				<div className="info_wrapper_decor">
					<img src={imgSrc("plus.svg")} alt="icon"/>
				</div>
			</div>
		</div>;
	},
});