const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Button, ToggleControl} = wp.components;
const {__} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

const slideAttributes = {
	background: {
		attribute: 'style',
		selector: '.screen_section',
		default: imgSrc('bg2.jpg')
	},

  headSubtitle :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__head-subtitle',
    default: 'Why'
  },

  headTitle :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__head-title',
    default: 'choose'
  },

  itemSubtitle1 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-subtitle.one',
    default: 'ICONIC'
  },

  itemTitle1 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-title.one',
    default: 'BRAND'
  },

  itemTxt1 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-txt.one',
    default: 'The Nikon image is <br> associated with credibility, quality, and satisfaction <br> for our consumers.'
  },

  itemSubtitle2 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-subtitle.two',
    default: 'OUTSTANDING'
  },

  itemTitle2 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-title.two',
    default: 'INNOVATION'
  },

  itemTxt2 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-txt.two',
    default: 'Nikon has paved <br> the way to be the leader <br> in continuing to introduce <br> new technologies.'
  },

  itemSubtitle3 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-subtitle.three',
    default: 'UNIQUE'
  },

  itemTitle3 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-title.three',
    default: 'CONSUMER EXPERIENCE'
  },

  itemTxt3 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-txt.three',
    default: 'We excite people’s <br> passion for exploring <br> through our unique <br> consumer experience.'
  },

  itemSubtitle4 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-subtitle.four',
    default: 'STRONG'
  },

  itemTitle4 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-title.four',
    default: 'PARTNERSHIP'
  },

  itemTxt4 :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__board-txt.four',
    default: 'Nikon fosters healthy <br> vision by selecting <br> customers who embody <br> the same yearning.'
  },

  infoTitle :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__info-title',
    default: 'a Nikon'
  },

  infoSubtitle :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__info-subtitle',
    default: 'spectacle lens?'
  },

  infoDescr :{
    type: 'string',
    source: 'html',
    selector: '.main-slide__info-descr',
    default: 'Nikon is the perfect choice to improve your differentiation, attract premium <br> consumers and upgrade the perception <br> of your store.'
  },
};

registerBlockType('presentation/slide1', {
	title: __('Slide: #1', 'np'),
	icon: icon,
	category: 'nikon-catalog',
	attributes: slideAttributes,
	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
    };

		return <div className={className + " block-presentation-slide all-empty"} style={{backgroundImage: `url(${attributes.background})`}}>


      <div className="screen_body_wrapper start no_relative">
        <div className="main-slide">
          <div className="main-slide__head">
            <span className="main-slide__head-subtitle">
              <RichText
                onChange={content => setAttributes({headSubtitle: content})}
                value={attributes.headSubtitle}
                placeholder={slideAttributes.headSubtitle.default.replace(/(<([^>]+)>)/ig,"")}
              />
            </span>
            <span className="main-slide__head-title">
              <RichText
                onChange={content => setAttributes({headTitle: content})}
                value={attributes.headTitle}
                placeholder={slideAttributes.headTitle.default.replace(/(<([^>]+)>)/ig,"")}
              />
            </span>
          </div>
          <div className="main-slide__holder">
            <div className="main-slide__left">
              <div className="main-slide__board">
                <figure className="main-slide__board-decor">
                  <img src={imgSrc("plus.svg")} alt="decor"/>
                </figure>
                <div className="main-slide__board-row">
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle one">
                        <RichText
                          onChange={content => setAttributes({itemSubtitle1: content})}
                          value={attributes.itemSubtitle1}
                          placeholder={slideAttributes.itemSubtitle1.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                      <span className="main-slide__board-title one">
                        <RichText
                          onChange={content => setAttributes({itemTitle1: content})}
                          value={attributes.itemTitle1}
                          placeholder={slideAttributes.itemTitle1.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                    </div>
                    <div className="main-slide__board-txt one">
                      <RichText
                        onChange={content => setAttributes({itemTxt1: content})}
                        value={attributes.itemTxt1}
                        placeholder={slideAttributes.itemTxt1.default.replace(/(<([^>]+)>)/ig,"")}
                      />
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle two">
                        <RichText
                          onChange={content => setAttributes({itemSubtitle2: content})}
                          value={attributes.itemSubtitle2}
                          placeholder={slideAttributes.itemSubtitle2.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                      <span className="main-slide__board-title two">
                        <RichText
                          onChange={content => setAttributes({itemTitle2: content})}
                          value={attributes.itemTitle2}
                          placeholder={slideAttributes.itemTitle2.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                    </div>
                    <div className="main-slide__board-txt two">
                      <RichText
                        onChange={content => setAttributes({itemTxt2: content})}
                        value={attributes.itemTxt2}
                        placeholder={slideAttributes.itemTxt2.default.replace(/(<([^>]+)>)/ig,"")}
                      />
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle three">
                        <RichText
                          onChange={content => setAttributes({itemSubtitle3: content})}
                          value={attributes.itemSubtitle3}
                          placeholder={slideAttributes.itemSubtitle3.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                      <span className="main-slide__board-title three">
                        <RichText
                          onChange={content => setAttributes({itemTitle3: content})}
                          value={attributes.itemTitle3}
                          placeholder={slideAttributes.itemTitle3.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                    </div>
                    <div className="main-slide__board-txt three">
                      <RichText
                        onChange={content => setAttributes({itemTxt3: content})}
                        value={attributes.itemTxt3}
                        placeholder={slideAttributes.itemTxt3.default.replace(/(<([^>]+)>)/ig,"")}
                      />
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle four">
                        <RichText
                          onChange={content => setAttributes({itemSubtitle4: content})}
                          value={attributes.itemSubtitle4}
                          placeholder={slideAttributes.itemSubtitle4.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                      <span className="main-slide__board-title four">
                        <RichText
                          onChange={content => setAttributes({itemTitle4: content})}
                          value={attributes.itemTitle4}
                          placeholder={slideAttributes.itemTitle4.default.replace(/(<([^>]+)>)/ig,"")}
                        />
                      </span>
                    </div>
                    <div className="main-slide__board-txt four">
                      <RichText
                        onChange={content => setAttributes({itemTxt4: content})}
                        value={attributes.itemTxt4}
                        placeholder={slideAttributes.itemTxt4.default.replace(/(<([^>]+)>)/ig,"")}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="main-slide__right">
              <div className="main-slide__info">
                <span className="main-slide__info-title">
                  <RichText
                    onChange={content => setAttributes({infoTitle: content})}
                    value={attributes.infoTitle}
                    placeholder={slideAttributes.infoTitle.default.replace(/(<([^>]+)>)/ig,"")}
                  />
                </span>
                <span className="main-slide__info-subtitle">
                  <RichText
                    onChange={content => setAttributes({infoSubtitle: content})}
                    value={attributes.infoSubtitle}
                    placeholder={slideAttributes.infoSubtitle.default.replace(/(<([^>]+)>)/ig,"")}
                  />
                </span>
                <div className="main-slide__info-descr">
                  <RichText
                    onChange={content => setAttributes({infoDescr: content})}
                    value={attributes.infoDescr}
                    placeholder={slideAttributes.infoDescr.default.replace(/(<([^>]+)>)/ig,"")}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>;
	},
	save({attributes}) {

		return <div className="screen_section screen_section--not-padding" data-section="#_SLIDE_NUMBER" style={{backgroundImage: `url(${attributes.background})`}}>

      <div className="screen_body_wrapper start no_relative">
        <div className="main-slide opacity_animate">
        <div className="main-slide__head">
            <span className="main-slide__head-subtitle">
              <RichText.Content value={attributes.headSubtitle}/>
            </span>
            <span className="main-slide__head-title">
              <RichText.Content value={attributes.headTitle}/>
            </span>
          </div>
          <div className="main-slide__holder">
            <div className="main-slide__left">
              <div className="main-slide__board">
                <figure className="main-slide__board-decor">
                  <img src={imgSrc("plus.svg")} alt="decor"/>
                </figure>
                <div className="main-slide__board-row">
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle one">
                        <RichText.Content value={attributes.itemSubtitle1}/>
                      </span>
                      <span className="main-slide__board-title one">
                        <RichText.Content value={attributes.itemTitle1}/>
                      </span>
                    </div>
                    <div className="main-slide__board-txt one">
                      <RichText.Content value={attributes.itemTxt1}/>
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle two">
                        <RichText.Content value={attributes.itemSubtitle2}/>
                      </span>
                      <span className="main-slide__board-title two">
                        <RichText.Content value={attributes.itemTitle2}/>
                      </span>
                    </div>
                    <div className="main-slide__board-txt two">
                      <RichText.Content value={attributes.itemTxt2}/>
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle three">
                        <RichText.Content value={attributes.itemSubtitle3}/>
                      </span>
                      <span className="main-slide__board-title three">
                        <RichText.Content value={attributes.itemTitle3}/>
                      </span>
                    </div>
                    <div className="main-slide__board-txt three">
                      <RichText.Content value={attributes.itemTxt3}/>
                    </div>
                  </div>
                  <div className="main-slide__board-item">
                    <div className="main-slide__board-head">
                      <span className="main-slide__board-subtitle four">
                        <RichText.Content value={attributes.itemSubtitle4}/>
                      </span>
                      <span className="main-slide__board-title four">
                        <RichText.Content value={attributes.itemTitle4}/>
                      </span>
                    </div>
                    <div className="main-slide__board-txt four">
                      <RichText.Content value={attributes.itemTxt4}/>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="main-slide__right">
              <div className="main-slide__info">
                <span className="main-slide__info-title">
                  <RichText.Content value={attributes.infoTitle}/>
                </span>
                <span className="main-slide__info-subtitle">
                  <RichText.Content value={attributes.infoSubtitle}/>
                </span>
                <div className="main-slide__info-descr">
                  <RichText.Content value={attributes.infoDescr}/>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
		</div>;
	},
});
