import BrandWrapper from '../../../subcomponents/brand-wrapper';

const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Button, ToggleControl} = wp.components;
const {__} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

const slideAttributes = {
	background: {
		attribute: 'style',
		selector: '.screen_section',
		default: imgSrc('office/bg-office-01.png')
	},
	slideTitle: {
		type: 'string',
		selector: '.brand_wrapper .gold',
		default: 'THE SOLUTION FOR YOUR INDOOR LIFESTYLE',
		source: 'html',
	},
	slideSubTitle: {
		type: 'string',
		selector: '.brand_wrapper .white',
		default: 'Extended Intermediate Viewing Zone',
		source: 'html',
	},

	boardTitle: {
		type: 'string',
		source: 'html',
		selector: '.of-advantages__board-title',
		default: 'CONVENTIONAL<br>PROGRESSIVE LENSES'
	},

	iconUrl: {
		attribute: 'src',
		selector: '.of-advantages__board-icon img',
		default: imgSrc("office/icon-office.svg")
	},

	imgUrl1: {
		attribute: 'src',
		selector: '.of-advantages__board-img img',
		default: imgSrc('office/of-advantages-01.png')
	},

	imgUrl2: {
		attribute: 'src',
		selector: '.of-advantages__board-img img',
		default: imgSrc('office/of-advantages-02.png')
	},

	description: {
		type: 'string',
		source: 'html',
		selector: '.of-advantages__board-descr',
		default: 'POWER AREA FOR INDOOR <br>USE INCREASED BY'
	},

	boardVal: {
		type: 'string',
		selector: '.of-advantages__board-val .of-advantages__board-val-item',
		default: '50',
		source: 'html',
	},
	boardPercent: {
		type: 'string',
		selector: '.of-advantages__board-val-percent',
		default: '%',
		source: 'html',
	},

	items: {
		type: 'array',
		source: 'query',
		selector: '.of-advantages__board-list-item',
		default: [
			{
				name: 'Far',
			},
			{
				name: 'Indoor purpose',
			},
			{
				name: 'At hand',
			},
		],
		query: {
			name: {
				type: 'string',
				source: 'html',
			},
		},
	},
};

registerBlockType('presentation/slide81', {
	title: __('Slide: #81', 'np'),
	icon: icon,
	category: 'nikon-catalog',
	attributes: slideAttributes,
	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
		};

		const item = (i) => {
			return <li className="of-advantages__board-list-item">
				<RichText
					onChange={content => {
						let items = attributes.items.slice();
						items[i].name = content;
						setAttributes({items: items});
					}}
					value={attributes.items && attributes.items[i] ? attributes.items[i].name : null}
				/>
			</li>
		}

		return <div className={className + " block-presentation-slide all-empty"}
					style={{backgroundImage: `url(${attributes.background})`}}>

			<InspectorControls>
				<h3>{__('Pick background image', 'np')}:</h3>
				<MediaUpload
					onSelect={media => {
						setAttributes({background: media.url});
					}}
					type="image"
					value={attributes.imageID}
					render={({open}) => getImageButton(open, attributes.background)}
				/>
			</InspectorControls>

			<div className="brand_wrapper">
					<span className="gold">
						<RichText
							onChange={content => setAttributes({slideTitle: content})}
							value={attributes.slideTitle}
							className="slide-title-input"
						/>
						 </span>
				<span className="white opacity_animate">
							<RichText
								onChange={content => setAttributes({slideSubTitle: content})}
								value={attributes.slideSubTitle}
								className="slide-subtitle-input"
							/>
					</span>
			</div>

			<div className="screen_body_wrapper start bottom bottom--mod no_relative">
				<div className="of-advantages">
					<div class="of-advantages__board">
						<div class="of-advantages__board-head">
							<div class="of-advantages__board-head-item">
                <span class="of-advantages__board-title">
                  <RichText
					  onChange={content => setAttributes({boardTitle: content})}
					  value={attributes.boardTitle}
				  />
                </span>
							</div>
							<div class="of-advantages__board-head-item">
								<figure class="of-advantages__board-icon">
									<MediaUpload
										onSelect={media => setAttributes({iconUrl: media.url})}
										type="image"
										value={attributes.imageID}
										render={({open}) => getImageButton(open, attributes.iconUrl)}
									/>
								</figure>
							</div>
						</div>
						<div class="of-advantages__board-content">
							<div class="of-advantages__board-decor">
								<figure class="of-advantages__board-arrows">
									<img src={imgSrc("office/of-advantages-arrows.png")} alt="img"/>
								</figure>
								<figure class="of-advantages__board-line">
									<img src={imgSrc("office/of-advantages-line-01.png")} alt="img"/>
								</figure>
							</div>
							<figure class="of-advantages__board-img">
								<MediaUpload
									onSelect={media => setAttributes({imgUrl1: media.url})}
									type="image"
									value={attributes.imageID}
									render={({open}) => getImageButton(open, attributes.imgUrl1)}
								/>
							</figure>
							<ul class="of-advantages__board-list">
								{attributes.items.map((el, i) => {
									return item(i);
								})}
							</ul>
							<figure class="of-advantages__board-img">
								<MediaUpload
									onSelect={media => setAttributes({imgUrl2: media.url})}
									type="image"
									value={attributes.imageID}
									render={({open}) => getImageButton(open, attributes.imgUrl2)}
								/>
							</figure>
						</div>
						<div class="of-advantages__board-bottom">
							<div class="of-advantages__board-info">
                <span class="of-advantages__board-descr">
                  <RichText
					  onChange={content => setAttributes({description: content})}
					  value={attributes.description}
				  />
                </span>
				<span class="of-advantages__board-val">
					<span className="of-advantages__board-val-item">
						<RichText
							onChange={content => setAttributes({boardVal: content})}
							value={attributes.boardVal}
						/>
					</span>
					<span className="of-advantages__board-val-percent">
						<RichText
							onChange={content => setAttributes({boardPercent: content})}
							value={attributes.boardPercent}
						/>
					</span>
                </span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>;
	},
	save({attributes}) {

		const item = (i) => {
			return <li className="of-advantages__board-list-item">
				<RichText.Content value={attributes.items[i].name}/>
			</li>
		}

		return <div className="screen_section screen_section--not-padding" data-section="#_SLIDE_NUMBER"
					style={{backgroundImage: `url(${attributes.background})`}}>

			<div className="brand_wrapper">
				<span className="gold"><RichText.Content value={attributes.slideTitle}/></span>
				<span className="white opacity_animate"><RichText.Content value={attributes.slideSubTitle}/></span>
			</div>

			<div className="screen_body_wrapper start bottom bottom--mod no_relative">
				<div className="of-advantages opacity_animate">
					<div class="of-advantages__board">
						<div class="of-advantages__board-head">
							<div class="of-advantages__board-head-item">
                <span class="of-advantages__board-title">
                  <RichText.Content value={attributes.boardTitle}/>
                </span>
							</div>
							<div class="of-advantages__board-head-item">
								<figure class="of-advantages__board-icon">
									<img src={attributes.iconUrl}/>
								</figure>
							</div>
						</div>
						<div class="of-advantages__board-content">
							<div class="of-advantages__board-decor">
								<figure class="of-advantages__board-arrows">
									<img src={imgSrc("office/of-advantages-arrows.png")} alt="img"/>
								</figure>
								<figure class="of-advantages__board-line">
									<img src={imgSrc("office/of-advantages-line-01.png")} alt="img"/>
								</figure>
							</div>
							<figure class="of-advantages__board-img">
								<img src={attributes.imgUrl1}/>
							</figure>
							<ul class="of-advantages__board-list">
								{attributes.items.map((el, i) => {
									return item(i);
								})}
							</ul>
							<figure class="of-advantages__board-img">
								<img src={attributes.imgUrl2}/>
							</figure>
						</div>
						<div class="of-advantages__board-bottom">
							<div class="of-advantages__board-info">
                <span class="of-advantages__board-descr">
                  <RichText.Content value={attributes.description}/>
                </span>
				<span class="of-advantages__board-val">
					<span className="of-advantages__board-val-item"><RichText.Content value={attributes.boardVal}/></span>			
					<span className="of-advantages__board-val-percent"><RichText.Content value={attributes.boardPercent}/></span>			
                </span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>;
	},
});
