// Finished
import BrandWrapper from '../../../subcomponents/brand-wrapper';
import {namedAttrObj, imgUploader, videoUploader} from '../../../utils';

const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Modal, Button, PanelRow, PanelBody} = wp.components;
const {withState} = wp.compose;
const {__, sprintf} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}


registerBlockType('presentation/slide27', {
	title: __('Slide: #27 Vision Studio', 'np'),
	icon: icon,
	category: 'nikon-presentations',
	attributes: {
		slideTitle: {
			type: 'string',
			selector: '.brand_wrapper .gold',
			default: 'CONSUMER EXPERIENCE',
			source: 'html',
		},
		slideSubTitle: {
			type: 'string',
			selector: '.brand_wrapper .white',
			default: 'Vision Studio',
			source: 'html',
		},
		mainImage: {
			type: 'string',
			source: 'attribute',
			attribute: 'src',
			selector: '.studio-decor img',
			default: imgSrc('studio/studio@2x.png')
		},
		studioDescription: {
			type: 'string',
			selector: '.studio__descr p',
			source: 'html',
			default: 'The Studio brings the lens into the store, <span style="color: #c09800" class="artb-font-color">helping the customer</span> to make their lens selection <span style="color: #c09800" class="artb-font-color">and encouraging high-end choices</span>'
		},
		touchAmazed: {
			type: 'string',
			selector: '.studio__caption',
			source: 'html',
			default: 'Touch & be amazed',
		},
		/*
				studioItem1Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="1"] .studio__preview-item-name'
				},
				studioItem1Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="1"] .studio__preview-item-img img'
				},
				studioItem1Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="1"] .slide-popup video'
				},

				studioItem2Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="2"] .studio__preview-item-name'
				},
				studioItem2Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="2"] .studio__preview-item-img img'
				},
				studioItem2Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="2"] .slide-popup video'
				},

				studioItem3Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="3"] .studio__preview-item-name'
				},
				studioItem3Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="3"] .studio__preview-item-img img'
				},
				studioItem3Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="3"] .slide-popup video'
				},

				studioItem4Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="4"] .studio__preview-item-name'
				},
				studioItem4Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="4"] .studio__preview-item-img img'
				},
				studioItem4Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="4"] .slide-popup video'
				},

				studioItem5Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="5"] .studio__preview-item-name'
				},
				studioItem5Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="5"] .studio__preview-item-img img'
				},
				studioItem5Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="5"] .slide-popup video'
				},

				studioItem6Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="6"] .studio__preview-item-name'
				},
				studioItem6Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="6"] .studio__preview-item-img img'
				},
				studioItem6Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="6"] .slide-popup video'
				},

				studioItem7Title: {
					type: 'string',
					default: '',
					selector: '.studio__preview-item[data-item="7"] .studio__preview-item-name'
				},
				studioItem7Preview: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="7"] .studio__preview-item-img img'
				},
				studioItem7Video: {
					attribute: 'src',
					selector: '.studio__preview-item[data-item="7"] .slide-popup video'
				},*/

		upto1Title: {
			type: 'string',
			selector: '.studio__info-item[data-item="1"] .studio__info-title',
			source: 'html',
			default: '<span style="font-size: 27px" class="artb-font-size">UP TO</span><br><span style="font-size: 73px" class="artb-font-size">18</span> pts<br><span style="font-size: 20px" class="artb-font-size">RISE IN LEVEL</span><br><span style="font-size: 20px" class="artb-font-size">OF HIGH-END</span><br><span style="font-size: 20px" class="artb-font-size">PROGRESSIVE </span><br><span style="font-size: 20px" class="artb-font-size">LENSES</span>'
		},

		upto2Title: {
			type: 'string',
			selector: '.studio__info-item[data-item="2"] .studio__info-title',
			source: 'html',
			default: '<span style="font-size: 27px" class="artb-font-size">UP TO</span><br><span style="font-size: 73px" class="artb-font-size">4</span> pts<br><span style="font-size: 20px" class="artb-font-size">RISE IN LEVEL </span><br><span style="font-size: 20px" class="artb-font-size">OF ANTI-UV </span><br><span style="font-size: 20px" class="artb-font-size">COATING</span>'
		},

	},


	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
		};


		const StudioInfoItem = i => {
			return <div className="studio__info-item">
				<div className="studio__info-icon">
					<img src={window.imgSrc('arrow-border.png')} alt="arrow-icon"/>
				</div>
				<div className="studio__info-content">
					<span className="studio__info-title">
						<RichText
							value={attributes[`upto${i}Title`]}
							placeholder="Up to"
							onChange={content => setAttributes(namedAttrObj(`upto${i}Title`, content))}
						/>
					</span>
				</div>
			</div>
		};

		console.log(attributes);

		return <div className={className + " block-presentation-slide all-empty screen_section--equal-paddings"}
					style={img('bg/bg-leanswear@2x.jpg')}>

			<div className="brand_wrapper">
				<span className="gold">
					<RichText
						onChange={content => setAttributes({slideTitle: content})}
						value={attributes.slideTitle}
						placeholder="CONSUMER EXPERIENCE"
						className="slide-title-input"
					/>
				</span>
				<span className="white opacity_animate">
					<RichText
						onChange={content => setAttributes({slideSubTitle: content})}
						value={attributes.slideSubTitle}
						placeholder="Visibly unique shop positioning"
						className="slide-subtitle-input"
					/>
				</span>
			</div>

			<div className="screen_body_wrapper no_relative">
				<div className="studio ">
					<div className="studio__wrap">
						<div className="studio__left">
							<div className="studio__descr">

								<p>
									<RichText
										onChange={content => setAttributes({studioDescription: content})}
										value={attributes.studioDescription}
										placeholder="The Studio brings the lens into the store, helping the customer to make their lens selection and encouraging high-end choices"
									/>

								</p>
							</div>
							<div className="studio__info">
								{StudioInfoItem(1)}
								{StudioInfoItem(2)}
							</div>
						</div>
						<div className="studio__right">
							<div className="studio-decor">

							</div>

							<span className="studio__caption">
								<RichText
									value={attributes.touchAmazed}
									placeholder="Touch & be amazed"
									onChange={content => setAttributes({touchAmazed: content})}
								/>
							</span>

							<div className="studio__preview">
								<div className="studio__preview-row">
									<div className="studio__preview-col studio__preview-col--left"/>
									<div className="studio__preview-col studio__preview-col--center">
										<figure className="studio__preview-img">
											<MediaUpload
												onSelect={media => {
													setAttributes({mainImage: media.url});
												}}
												type="image"
												value={attributes.imageID}
												render={({open}) => getImageButton(open, attributes.mainImage)}
											/>
										</figure>
									</div>
									<div className="studio__preview-col studio__preview-col--right"/>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>;
	},

	save({attributes}) {


		const StudioInfoItem = i => {

			return (attributes[`upto${i}Title`] || attributes[`upto${i}Num`] || attributes[`upto${i}Text`] || attributes[`upto${i}Caption`]) &&
				<div data-item={i} className="studio__info-item">
					<div className="studio__info-icon">
						<img src={imgSrc("arrow-border.png")} alt="arrow-icon"/>
					</div>
					<div className="studio__info-content">
						{attributes[`upto${i}Title`] &&
						<span className="studio__info-title"><RichText.Content
							value={attributes[`upto${i}Title`]}/></span>
						}
					</div>
				</div>
		};



		return <div className="screen_section screen_section--equal-paddings" data-section="#_SLIDE_NUMBER"
					style={window.img('tiles-grid-bg.png')}>
			<div className="brand_wrapper">
				<span className="gold"><RichText.Content value={attributes.slideTitle}/></span>
				<span className="white opacity_animate"><RichText.Content value={attributes.slideSubTitle}/></span>
			</div>
			<div className="screen_body_wrapper no_relative">
				<div className="studio opacity_animate">
					<div className="studio__wrap">
						<div className="studio__left">
							{attributes.studioDescription &&
							<div className="studio__descr">
								<p><RichText.Content value={attributes.studioDescription}/></p>
							</div>
							}
							<div className="studio__info">
								{StudioInfoItem(1)}
								{StudioInfoItem(2)}
							</div>
						</div>
						<div className="studio__right">

							{attributes.touchAmazed &&
							<span className="studio__caption"><RichText.Content value={attributes.touchAmazed}/></span>
							}
							<div className="studio__preview">
								<div className="studio__preview-row">
									<div className="studio__preview-col studio__preview-col--left">

									</div>
									<div className="studio__preview-col studio__preview-col--center">
										{attributes.mainImage &&
										<figure className="studio__preview-img">
											<img src={attributes.mainImage}/>
										</figure>
										}

									</div>
									<div className="studio__preview-col studio__preview-col--right">

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>;
	},
});
