import BrandWrapper from  '../../../subcomponents/brand-wrapper';
const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Button, ToggleControl} = wp.components;
const {__} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

const slideAttributes = {
  background: {
		attribute: 'style',
		selector: '.screen_section',
		default: imgSrc('advance/bg-advance.png')
  },

	slideTitle: {
		type: 'string',
		selector: '.brand_wrapper .gold',
    default: 'SIGNATURE SOLUTION FOR DIGITALLY OPTIMIZED VISION',
    source: 'html',
	},
  description: {
    type: 'string',
    selector: '.wd-reduce__board-descr',
    source: 'html',
    default: 'THE SIGNATURE OF NIKON, PRESIO ADVANCE COMBINES <span>UNPRECEDENTED SHARPNESS WITH SUPERIOR COMFORT</span> TO DELIVER A HIGH QUALITY ALL-PURPOSE LENS FOR ALL WEARERS'
  },
	imageUrl: {
		attribute: 'src',
		selector: '.wd-reduce__board-img img',
		default: imgSrc("advance/adv-sharpness.jpg")
	},
};

registerBlockType('presentation/slide96', {
	title: __('Slide: #96', 'np'),
	icon: icon,
	category: 'nikon-catalog',
	attributes: slideAttributes,
	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
		};

		return <div className={className + " block-presentation-slide all-empty"} style={{backgroundImage: `url(${attributes.background})`}}>
      <InspectorControls>
				<h3>{__('Pick background image:', 'np')}</h3>
				<MediaUpload
					onSelect={media => {
						setAttributes({background: media.url});
					}}
					type="image"
					value={attributes.imageID}
					render={({open}) => getImageButton(open, attributes.background)}
				/>
				<br/>
				<br/>
			</InspectorControls>

      <div className="brand_wrapper">
        <span className="gold">
          <RichText
            onChange={content => setAttributes({slideTitle: content})}
            value={attributes.slideTitle}
            placeholder="SIGNATURE SOLUTION FOR DIGITALLY OPTIMIZED VISION"
            className="slide-title-input"
          />
        </span>
			</div>

      <div className="screen_body_wrapper start no_relative">
        <div className="wd-reduce">
          <div className="wd-reduce__board">
            <figure className="wd-reduce__board-img">
              <MediaUpload
                onSelect={media => setAttributes({imageUrl: media.url})}
                type="image"
                value={attributes.imageID}
                render={({open}) => getImageButton(open, attributes.imageUrl)}
              />
            </figure>
            <span className="wd-reduce__board-descr">
              <RichText
                onChange={content => setAttributes({description: content})}
                value={attributes.description}
                placeholder={slideAttributes.description.default.replace(/(<([^>]+)>)/ig,"")}
              />
            </span>
          </div>
        </div>
      </div>
    </div>;
	},
	save({attributes}) {

		return <div className="screen_section screen_section--not-padding" data-section="#_SLIDE_NUMBER" style={{backgroundImage: `url(${attributes.background})`}}>


				<div className="brand_wrapper">
					<span className="gold">
            <RichText.Content value={attributes.slideTitle}/>
          </span>
				</div>

      <div className="screen_body_wrapper start no_relative">
        <div className="wd-reduce opacity_animate">
        <div className="wd-reduce__board">
            <figure className="wd-reduce__board-img">
              <img src={attributes.imageUrl}/>
            </figure>
            <span className="wd-reduce__board-descr">
              <RichText.Content value={attributes.description}/>
            </span>
          </div>
        </div>
      </div>

		</div>;
	},
});
