import BrandWrapper from  '../../../subcomponents/brand-wrapper';
const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Button, ToggleControl} = wp.components;
const {__} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

const slideAttributes = {
	background: {
		attribute: 'style',
		selector: '.screen_section',
		default: imgSrc('bright/bg-bright.png')
	},

	slideTitle: {
		type: 'string',
		selector: '.brand_wrapper .gold',
    default: 'TECHNOLOGY',
    source: 'html',
  },

  headText :{
    type: 'string',
    selector: '.br-technology__board-head',
    default: 'A REVOLUTIONARY BRIGHTENING TECHNOLOGY',
    source: 'html',
  },

  decorText :{
    type: 'string',
    selector: '.br-technology__decor-txt',
    default: 'Brightening layer',
    source: 'html',
  },

  infoVal :{
    type: 'string',
    selector: '.br-technology__info-val',
    default: '91',
    source: 'html',
  },

  description :{
    type: 'string',
    source: 'html',
    selector: '.br-technology__info-descr',
    default: 'of wearers <br> see an <br> improvement *'
  },

  footText :{
    type: 'string',
    selector: '.br-technology__foot',
    default: '*Source : QUT (Queensland University of Technology clinical study on 45 participants aged between 40 to 69 y.o., April 2017',
    source: 'html',
  },
};

registerBlockType('presentation/slide75', {
	title: __('Slide: #75', 'np'),
	icon: icon,
	category: 'nikon-catalog',
	attributes: slideAttributes,
	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
    };

		return <div className={className + " block-presentation-slide all-empty"} style={{backgroundImage: `url(${attributes.background})`}}>

      <InspectorControls>
        <h3>{__('Pick background image', 'np')}:</h3>
        <MediaUpload
          onSelect={media => {
            setAttributes({background: media.url});
          }}
          type="image"
          value={attributes.imageID}
          render={({open}) => getImageButton(open, attributes.background)}
        />
      </InspectorControls>

      <div className="brand_wrapper">
        <span className="gold">
          <RichText
            onChange={content => setAttributes({slideTitle: content})}
            value={attributes.slideTitle}
            placeholder="TECHNOLOGY"
            className="slide-title-input"
          />
        </span>
			</div>

      <div className="screen_body_wrapper start bottom bottom--mod no_relative">
        <div class="br-technology">
          <div class="br-technology__board" style={img('bright/br-technology.png')}>
            <div class="br-technology__board-head">
              <RichText
                onChange={content => setAttributes({headText: content})}
                value={attributes.headText}
                placeholder={slideAttributes.headText.default.replace(/(<([^>]+)>)/ig,"")}
              />
            </div>
            <div class="br-technology__decor">
              <span class="br-technology__decor-txt">
                <RichText
                  onChange={content => setAttributes({decorText: content})}
                  value={attributes.decorText}
                  placeholder={slideAttributes.decorText.default.replace(/(<([^>]+)>)/ig,"")}
                />
              </span>
            </div>
            <div class="br-technology__info">
              <span class="br-technology__info-val">
                <RichText
                  onChange={content => setAttributes({infoVal: content})}
                  value={attributes.infoVal}
                  placeholder={slideAttributes.infoVal.default.replace(/(<([^>]+)>)/ig,"")}
                />
              </span>
              <span class="br-technology__info-descr">
                <RichText
                  onChange={content => setAttributes({description: content})}
                  value={attributes.description}
                  placeholder={slideAttributes.description.default.replace(/(<([^>]+)>)/ig,"")}
                />
              </span>
            </div>
          </div>
          <div class="br-technology__foot">
            <RichText
              onChange={content => setAttributes({footText: content})}
              value={attributes.footText}
              placeholder={slideAttributes.footText.default.replace(/(<([^>]+)>)/ig,"")}
            />
          </div>
        </div>
      </div>
    </div>;
	},
	save({attributes}) {

		return <div className="screen_section screen_section--not-padding" data-section="#_SLIDE_NUMBER" style={{backgroundImage: `url(${attributes.background})`}}>

      <div className="brand_wrapper">
        <span className="gold">
          <RichText.Content value={attributes.slideTitle}/>
        </span>
      </div>

      <div className="screen_body_wrapper start bottom bottom--mod no_relative">
        <div class="br-technology opacity_animate">
          <div class="br-technology__board" style={img('bright/br-technology.png')}>
            <div class="br-technology__board-head">
              <RichText.Content value={attributes.headText}/>
            </div>
            <div class="br-technology__decor">
              <span class="br-technology__decor-txt">
                <RichText.Content value={attributes.decorText}/>
              </span>
            </div>
            <div class="br-technology__info">
              <span class="br-technology__info-val">
                <RichText.Content value={attributes.infoVal}/>
              </span>
              <span class="br-technology__info-descr">
                <RichText.Content value={attributes.description}/>
              </span>
            </div>
          </div>
          <div class="br-technology__foot">
            <RichText.Content value={attributes.footText}/>
          </div>
        </div>
      </div>
		</div>;
	},
});
