import BrandWrapper from  '../../../subcomponents/brand-wrapper';
const {RichText, PlainText, InnerBlocks, InspectorControls, MediaUpload} = wp.editor;
const {registerBlockType} = wp.blocks;
const {Fragment} = wp.element;
const {SelectControl, Button, ToggleControl} = wp.components;
const {__} = wp.i18n;

try {
	var icon = require('./icon').default; //Icon is generated by bash script in the theme root. Use "bash convert-thumbnails-to-svg.bash"
} catch (ex) {
	var icon = 'editor-code';
}

const slideAttributes = {
	background: {
		attribute: 'style',
		selector: '.screen_section',
		default: imgSrc('relaxsee/bg-relaxsee.png')
	},

	title :{
    type: 'string',
    selector: '.rs-what__title',
    default: 'WHAT ARE THE CAUSES OF EYESTRAIN?',
    source: 'html',
  },

  boardTitle1 :{
    type: 'string',
    selector: '.rs-what__board-title.first',
    default: 'FOCUSING ON FAR DISTANCE',
    source: 'html',
  },

  boardTitle2 :{
    type: 'string',
    selector: '.rs-what__board-title.second',
    default: 'AT REST',
    source: 'html',
  },

  boardTitle3 :{
    type: 'string',
    selector: '.rs-what__board-title.third',
    default: 'FOCUSING ON NEAR DISTANCE',
    source: 'html',
  },

  boardTitle4 :{
    type: 'string',
    selector: '.rs-what__board-title.four',
    default: 'WORKING',
    source: 'html',
  },

  itemName1 :{
    type: 'string',
    selector: '.rs-what__board-name.first',
    default: 'Crystalline lens',
    source: 'html',
  },

  itemName2 :{
    type: 'string',
    selector: '.rs-what__board-name.second',
    default: 'Ciliary muscle',
    source: 'html',
  },

  itemName3 :{
    type: 'string',
    selector: '.rs-what__board-name.third',
    default: 'Ciliary muscle',
    source: 'html',
  },

  boardCaption :{
    type: 'string',
    selector: '.rs-what__board-caption',
    default: 'NEAR DISTANCE WORK',
    source: 'html',
  },

  boardTxt :{
    type: 'string',
    source: 'html',
    selector: '.rs-what__board-txt',
    default: 'When the eye focuses on near distance items, the ciliary muscle needs to work to bend the crystalline lens.<br>This puts strain on the muscle, and after many hours of effort, the muscle gets tired.'
  },

  boardDescr :{
    type: 'string',
    source: 'html',
    selector: '.rs-what__board-descr',
    default: 'RELAXSEE NEO <span>RELIEVES THE EFFORT</span> OF THE CILIARY MUSCLE TO REDUCE EYESTRAIN.'
  },

};

registerBlockType('presentation/slide88', {
	title: __('Slide: #88', 'np'),
	icon: icon,
	category: 'nikon-catalog',
	attributes: slideAttributes,
	edit({className, attributes, setAttributes}) {

		const getImageButton = (openEvent, value) => {

			if (value)
				return (
					<img
						src={value}
						onClick={openEvent}
						className="image"
					/>
				);

			return (
				<div className="button-container">
					<Button
						onClick={openEvent}
						className="button button-large"
					>
						{__('Pick an image', 'np')}
					</Button>
				</div>
			);
    };

		return <div className={className + " block-presentation-slide all-empty"} style={{backgroundImage: `url(${attributes.background})`}}>

      <InspectorControls>
        <h3>{__('Pick background image', 'np')}:</h3>
        <MediaUpload
          onSelect={media => {
            setAttributes({background: media.url});
          }}
          type="image"
          value={attributes.imageID}
          render={({open}) => getImageButton(open, attributes.background)}
        />
      </InspectorControls>

      <div className="screen_body_wrapper start bottom bottom--mod no_relative">
        <div className="rs-what">
          <span className="rs-what__title">
            <RichText
              onChange={content => setAttributes({title: content})}
              value={attributes.title}
            />
          </span>
          <div className="rs-what__board">
            <div className="rs-what__board-holder">
              <figure className="rs-what__board-arrow">
                <img src={imgSrc("relaxsee/rs-what-arrow.png")} alt="img"/>
              </figure>
              <div className="rs-what__board-inner">
                <span className="rs-what__board-title first">
                  <RichText
                    onChange={content => setAttributes({boardTitle1: content})}
                    value={attributes.boardTitle1}
                  />
                </span>
                <div className="rs-what__board-item">
                  <figure className="rs-what__board-img">
                    <img src={imgSrc("relaxsee/rs-what-01.png")} alt="img"/>
                  </figure>
                  <span className="rs-what__board-name top first">
                    <RichText
                      onChange={content => setAttributes({itemName1: content})}
                      value={attributes.itemName1}
                    />
                  </span>
                  <span className="rs-what__board-name bottom second">
                    <RichText
                      onChange={content => setAttributes({itemName2: content})}
                      value={attributes.itemName2}
                    />
                  </span>
                </div>
                <span className="rs-what__board-title second">
                  <RichText
                    onChange={content => setAttributes({boardTitle2: content})}
                    value={attributes.boardTitle2}
                  />
                </span>
              </div>
              <div className="rs-what__board-inner mod">
                <span className="rs-what__board-title third">
                  <RichText
                    onChange={content => setAttributes({boardTitle3: content})}
                    value={attributes.boardTitle3}
                  />
                </span>
                <div className="rs-what__board-item">
                  <figure className="rs-what__board-img">
                    <img src={imgSrc("relaxsee/rs-what-02.png")} alt="img"/>
                  </figure>
                  <span className="rs-what__board-name bottom third">
                    <RichText
                      onChange={content => setAttributes({itemName3: content})}
                      value={attributes.itemName3}
                    />
                  </span>
                </div>
                <span className="rs-what__board-title four">
                  <RichText
                    onChange={content => setAttributes({boardTitle4: content})}
                    value={attributes.boardTitle4}
                  />
                </span>
              </div>
            </div>
            <div className="rs-what__board-bottom">
              <span className="rs-what__board-caption">
                <RichText
                  onChange={content => setAttributes({boardCaption: content})}
                  value={attributes.boardCaption}
                />
              </span>
              <div className="rs-what__board-txt">
                <RichText
                  onChange={content => setAttributes({boardTxt: content})}
                  value={attributes.boardTxt}
                />
              </div>
              <span className="rs-what__board-descr">
                <RichText
                  onChange={content => setAttributes({boardDescr: content})}
                  value={attributes.boardDescr}
                />
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>;
	},
	save({attributes}) {

		return <div className="screen_section screen_section--not-padding" data-section="#_SLIDE_NUMBER" style={{backgroundImage: `url(${attributes.background})`}}>

      <div className="screen_body_wrapper start bottom bottom--mod no_relative">
        <div className="rs-what opacity_animate">
          <span className="rs-what__title">
            <RichText.Content value={attributes.title}/>
          </span>
          <div className="rs-what__board">
            <div className="rs-what__board-holder">
              <figure className="rs-what__board-arrow">
                <img src={imgSrc("relaxsee/rs-what-arrow.png")} alt="img"/>
              </figure>
              <div className="rs-what__board-inner">
                <span className="rs-what__board-title first">
                  <RichText.Content value={attributes.boardTitle1}/>
                </span>
                <div className="rs-what__board-item">
                  <figure className="rs-what__board-img">
                    <img src={imgSrc("relaxsee/rs-what-01.png")} alt="img"/>
                  </figure>
                  <span className="rs-what__board-name top first">
                    <RichText.Content value={attributes.itemName1}/>
                  </span>
                  <span className="rs-what__board-name bottom second">
                    <RichText.Content value={attributes.itemName2}/>
                  </span>
                </div>
                <span className="rs-what__board-title second">
                  <RichText.Content value={attributes.boardTitle2}/>
                </span>
              </div>
              <div className="rs-what__board-inner mod">
                <span className="rs-what__board-title third">
                  <RichText.Content value={attributes.boardTitle3}/>
                </span>
                <div className="rs-what__board-item">
                  <figure className="rs-what__board-img">
                    <img src={imgSrc("relaxsee/rs-what-02.png")} alt="img"/>
                  </figure>
                  <span className="rs-what__board-name bottom third">
                    <RichText.Content value={attributes.itemName3}/>
                  </span>
                </div>
                <span className="rs-what__board-title four">
                  <RichText.Content value={attributes.boardTitle4}/>
                </span>
              </div>
            </div>
            <div className="rs-what__board-bottom">
              <span className="rs-what__board-caption">
                <RichText.Content value={attributes.boardCaption}/>
              </span>
              <div className="rs-what__board-txt">
                <RichText.Content value={attributes.boardTxt}/>
              </div>
              <span className="rs-what__board-descr">
                <RichText.Content value={attributes.boardDescr}/>
              </span>
            </div>
          </div>
        </div>
      </div>
		</div>;
	},
});
